services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: order_management_by_zahin_2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure:2

  redis:
    container_name: redis
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS:-nestjs_starter_demo}
    ports:
      - '6379:6379'
    restart: on-failure:2

  backend:
    build:
      context: ./backend
    ports:
      - "3010:3010"
    environment:
      - TARGET_ENV=development
      - PORT=5010
      - BACKEND_URL=http://127.0.0.1:5010
      - API_PREFIX=/api/v1
      - CONTAINER_NAME=nestjs-starter
      - DB_NAME=order_management_by_zahin_2
      - DATABASE_URL=postgresql://postgres:1234@localhost:5432/order_management_by_zahin_2
      - JWT_SECRET=VERYSECRETCODE
      - ACCESS_TOKEN_SECRET=#
      - SALT=12
      - MAX_FILE_SIZE=50
      - DISK_STORAGE=public/uploads
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_FAMILY=4
      - REDIS_DB=0
      - REDIS_PASS=${REDIS_PASS:-nestjs_starter_demo}
      - SECRET_ACCESS_KEY=#
      - ACCESS_KEY_ID=#
      - REGION=#
      - S3_BUCKET=#
      - SESSION_SECRET=nestjs_starter_demo
    depends_on:
      - db
      - redis
    restart: on-failure:3

  frontend:
    build:
      context: ./frontend
    ports:
      - "3179:3179"
    environment:
      - VITE_SERVER_ENDPOINT=http://localhost:5010
    depends_on:
      - backend
    restart: on-failure:2

volumes:
  pgdata:
  pgadmin-data:
