services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: order_management_by_zahin_2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure:2


  redis:
    container_name: redis
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS:-nestjs_starter_demo}
    ports:
      - '6379:6379'
    restart: on-failure:2

  backend:
    build:
      context: ./backend
    ports:
      - "3010:3010"
    environment:
      - TARGET_ENV=development
      - DATABASE_URL=postgresql://postgres:1234@db:5432/order_management_by_zahin_2
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: on-failure:3

  frontend:
    build:
      context: ./frontend
    ports:
      - "3179:3179"
    environment:
      - VITE_SERVER_ENDPOINT=http://localhost:3010
    depends_on:
      - backend
    restart: on-failure:2

volumes:
  pgdata:
  pgadmin-data:
